name: Daily Exchange Rates

on:
  schedule:
    - cron: '7 0 * * *' # every day at 00:07 UTC
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update-rates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Fetch latest rates
        run: |
          node --version
          npm --version || true
          node ./scripts/fetch_rates.mjs

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/rates-usd.json
          if git diff --cached --quiet; then
            echo "No changes in rates file. Skipping commit."
            exit 0
          fi
          git commit -m "chore(rates): update daily USD exchange rates"
          git push


